version: "3.7"
services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/shell/ || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 3
    ports:
      - "8000:8000"
    expose:
      - "8000"

  api:
    build:
      context: .
    depends_on:
      - dynamodb
    links:
      - dynamodb
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: "curl -f http://api/pingo"
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      VALID_API_TOKENS: ${VALID_API_TOKENS}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDER_EMAIL: ${SENDER_EMAIL}
      DYNAMODB_HOST: dynamodb
      DYNAMODB_PORT: 8000
      DYNAMODB_NO_START: "true"
